<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 C:\Users\tst\source\spike\anatomy-viewer\static\models\MaleCharBaseMesh.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()
  
  type GLTFResult = {
    nodes: {
      Body1: THREE.Mesh
      Body1_1: THREE.Mesh
      Body1_2: THREE.Mesh
      Body1003: THREE.Mesh
      Body1003_1: THREE.Mesh
      Body1003_2: THREE.Mesh
    }
    materials: {
      Char_lp: THREE.MeshStandardMaterial
      Eye: THREE.MeshStandardMaterial
      Eyel: THREE.MeshStandardMaterial
      Char_Mlp: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/MaleCharBaseMesh.glb')
  gltf.then(test => {console.log(test)});

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <!-- <T.Group position={[-0.7, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.Body1.geometry} material={gltf.materials.Char_lp} />
      <T.Mesh geometry={gltf.nodes.Body1_1.geometry} material={gltf.materials.Eye} />
      <T.Mesh geometry={gltf.nodes.Body1_2.geometry} material={gltf.materials.Eyel} />
    </T.Group> -->
    <T.Group position={[0, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.Body1003.geometry} material={gltf.materials.Char_Mlp}>
        <!-- <T.MeshStandardMaterial color="#cba590" /> -->
      </T.Mesh>
      <T.Mesh geometry={gltf.nodes.Body1003_1.geometry} material={gltf.materials.Eye} />
      <T.Mesh geometry={gltf.nodes.Body1003_2.geometry} material={gltf.materials.Eyel} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
